choi/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from users import views

urlpatterns = patterns('',
    # Examples:
    url(r'^$',  TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^projects/', include('repos.urls', namespace='repos')),
    url(r'^skills/$',  views.skills, name='skills'),
    url(r'^skills/(\w+)/$',  views.skill_by_slug, name='skill_by_slug'),
    url(r'^admin/', include(admin.site.urls)),
)

repos/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from repos import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', views.ProjectView.as_view(), name="project_detail"),
    url(r'^create$', views.ProjectCreateView.as_view(), name="project_create"),
    url(r'^(?P<pk>\d+)/edit$', views.ProjectUpdateView.as_view(), name="project_update"),
    url(r'^(?P<pk>\d+)/add_repo$', views.add_repo, name="add_repo"),
    url(r'^remove_repo$', views.remove_repo, name="remove_repo"),
    url(r'^(?P<project>\d+)/add_owner$', views.add_owner, name="add_owner"),
    url(r'^(?P<project>\d+)/remove_owner', views.remove_owner, name="remove_owner"),
)

users/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from users import views
from users.models import NICK_PATTERN

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name="list"),
    url(r'^(?P<slug>{})/$'.format(NICK_PATTERN), views.UserView.as_view(), name="detail"),
    url(r'^create$', views.UserCreateView.as_view(), name="user_create"),
    url(r'^(?P<slug>{})/edit$'.format(NICK_PATTERN), views.UserUpdateView.as_view(), name="user_update"),
)

repos/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse


class Project(models.Model):
    english_name = models.CharField(_('Project Name (English)'), unique=True, max_length=255, blank=True)
    hebrew_name = models.CharField(_('Project Name (Hebrew)'), unique=True, max_length=255, blank=True)
    description = models.TextField(_('Project Description'), blank=True)
    owner = models.ForeignKey('users.User',
                              related_name='projects',
                              blank=True,
                              null=True)

    def __unicode__(self):
        return self.english_name

    def get_absolute_url(self):
        return reverse('repos:project_detail', kwargs={'pk': self.pk})

# Repo = GitHub Repo. Each Hasadna Project may have one or more repos.
class Repo(models.Model):
    full_name = models.CharField(_('Repo full name ("username/repo_name")'), unique=True, max_length=255, blank=True)
    description = models.TextField(_('Repo description from github'), blank=True)
    last_fetch = models.DateTimeField(_('Last time commits were fetched'), auto_now=True, blank=False)
    project = models.ForeignKey('repos.Project',
                                  related_name='repos',
                                  blank=False,
                                  null=False)

class Commit(models.Model):
    author_github_username = models.CharField(_('Github username of author'),max_length=255, null=False, blank=False)
    author_name = models.CharField(_('Name of author according to github'),max_length=255, null=True, blank=True)
    author_url = models.CharField(_('Author Github page URL'), max_length=255, blank=True)
    author_email = models.CharField(_('Author email'), max_length=255, blank=True)
    author_date = models.DateTimeField(_('Author date'), blank=False)
    author = models.ForeignKey('users.User',
                                  related_name='authored_commits',
                                  blank=True,
                                  null=True,
                                  on_delete=models.SET_NULL)
    committer_github_username = models.CharField(_('Github username of committer'),max_length=255,null=False, blank=False)
    committer_name = models.CharField(_('Name of committer according to github'),max_length=255, null=True, blank=True)
    committer_url = models.CharField(_('Author Github page URL'), max_length=255, blank=True)
    committer_email = models.CharField(_('Committer email'), max_length=255, blank=True)
    committer_date = models.DateTimeField(_('Committer date'), blank=False)
    committer = models.ForeignKey('users.User',
                                     related_name='committed_commits',
                                     blank=True,
                                     null=True,
                                     on_delete=models.SET_NULL)
    sha = models.CharField(_('SHA'), max_length=255, blank=False)
    url = models.CharField(_('Commit URL'), max_length=255, blank=True)
    message = models.TextField(_('Commit message'), blank=True)
    imported_on = models.DateTimeField(_('Imported from Github on'), auto_now_add=True, blank=False)

class CommitRepo(models.Model):
    commit = models.ForeignKey('Commit', related_name='repos')
    repo = models.ForeignKey('Repo', related_name='commits')

class CommitParent(models.Model):
    child = models.ForeignKey('Commit', related_name='parents')
    parent = models.ForeignKey('Commit', related_name='children')

repos/forms.py
from repos.models import Project, Repo
from users.models import User
import floppyforms as forms


class EditProjectForm(forms.ModelForm):
    class Meta:
        model = Project


class AddRepoToProject(forms.ModelForm):
    class Meta:
        model = Repo
        fields = ['full_name']


class AddOwnerToProject(forms.Form):
    owner = forms.ModelChoiceField(queryset=User.objects.all())

repos/views.py
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from repos.models import Project, Repo
from users.models import User
from forms import EditProjectForm, AddRepoToProject, AddOwnerToProject
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

class HomeView(ListView):
    model = Project


class ProjectView(DetailView):
    model = Project

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        repos = self.object.repos.all()
        repo_commits = dict()
        for repo in repos:
            commit_repos = repo.commits.all()
            commits = [commitRepo.commit for commitRepo in commit_repos]
            repo_commits[repo]=commits
        context['repo_commits'] = repo_commits
        context['repo_form'] = AddRepoToProject(self.object.pk, self.request.POST)
        return context


class ProjectCreateView(CreateView):
    model = Project
    form_class = EditProjectForm
    template_name_suffix = '_create_form'


class ProjectUpdateView(UpdateView):
    model = Project
    form_class = EditProjectForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return self.object.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super(ProjectUpdateView, self).get_context_data(**kwargs)
        repos = self.object.repos.all()
        context['repos'] = repos
        context['repo_form'] = AddRepoToProject(self.request.POST)
        context['owner'] = self.object.owner
        context['owner_form'] = AddOwnerToProject(self.request.POST)
        return context


def add_repo(request, pk):
    if request.method == 'POST': # If the form has been submitted...
        form = AddRepoToProject(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            repo_name = form.cleaned_data['full_name']
            project = Project.objects.get(pk=pk)
            repo = project.repos.get_or_create(full_name=repo_name, project=project)
            return HttpResponseRedirect(reverse('repos:project_update',kwargs={'pk': project.pk})) # Redirect after POST


def remove_repo(request):
    if request.method == 'POST':
        repo_pk = request.POST['repo']
        repo = Repo.objects.get(pk=repo_pk)
        project = repo.project
        repo.delete()
        return HttpResponseRedirect(reverse('repos:project_update',kwargs={'pk': project.pk})) # Redirect after POST


def add_owner(request, project):
    if request.method == 'POST': # If the form has been submitted...
        form = AddOwnerToProject(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            owner = form.cleaned_data['owner']
            project = Project.objects.get(pk=project)
            project.owners.get_or_create(owner=owner, project=project)
            return HttpResponseRedirect(reverse('repos:project_update',kwargs={'pk': project.pk})) # Redirect after POST


def remove_owner(request, project):
    if request.method == 'POST':
        owner_pk = request.POST['owner']
        owner = User.objects.get(pk=owner_pk)
        project = Project.objects.get(pk=project)
        owner.projects.get(owner=owner, project=project).delete()
        return HttpResponseRedirect(reverse('repos:project_update',kwargs={'pk': project.pk})) # Redirect after POST

repos/templates/repos/project_create_form.html
{% extends "repos/project_form.html" %}
{% load i18n %}

{% block breadcrumbs %}
<li><a href="{%  url "repos:list" %}">{%  trans "Projects" %}</a></li>
<li class="active">{% trans "New Project" %}</li>
{% endblock %}

{% block form_action %}{% url 'repos:project_create' %}{% endblock %}

repos/templates/repos/project_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
<li><a href="{%  url "repos:list" %}">{%  trans "Projects" %}</a></li>
<li class="active">{{ object.english_name }}</li>
{% endblock %}

{% block content %}
<div class="well">
    <center>
        <h3 class="media-heading">{{ object.hebrew_name }} | {{ object.english_name }}</h3>
        <strong>Owner:</strong> 
        {% if object.owner %}
        <a href="{% url 'users:detail' object.owner.nick %}">{{ object.owner }}</a>
        {% endif %}
        <br>
        (<a href="{% url 'repos:project_update' object.pk %}">Edit</a>)

    </center>
    <hr>
    <p class="text-left"><strong>Description: </strong><br>
        {{object.description}}
    </p>
    {% if object.repos and object.repos.all|length > 0 %}
    <hr>
    <p class="text-left"><strong>Repositories and number of commits: </strong></p>

    {% for repo, commits in repo_commits.items %}
    {% if not repo == 'total_commits' %}
    <div class="panel-group" id="repo-accordion">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h4 class="panel-title">
                	<a href="http://github.com/hasadna/{{repo.full_name}}" target="_blank">
   	               	<span class="glyphicon glyphicon-link"></span>
   	               	</a>
                    <a data-toggle="collapse" data-parent="#" href="#collapseRepo{{forloop.counter}}">
                        {{repo.full_name}}: {{ commits | length}}
                    </a>
                </h4>
            </div>
            <div id="collapseRepo{{forloop.counter}}" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul class="list-group">
                        {%for commit in commits %}
                        <li class="list-group-item">{{commit.message}}</li>
                        {%endfor%}
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}
    {% endif %}

</div>
{% endblock %}

repos/templates/repos/project_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="well">

    <ul class="list-group">
        <form action="{% block form_action %}{% endblock %}" method="post">{% csrf_token %}
            {{ form.as_ul }}
            <input type="submit" value="Update" />
        </form>
    </ul>

    {% if object.repos and object.repos.all|length > 0 %}
    <hr>
    <p class="text-left"><strong>Connected Repositories: </strong></p>

    <ul class="list-group">
        {% for repo in repos %}
        <li class="list-group-item">
                <form role="inline-form" action="{% url 'repos:remove_repo' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="repo" value="{{repo.pk}}"/>
                    <button class="btn btn-link pull-right" type="submit" onclick="return confirm('{% trans 'Are you sure you want to remove this repo?' %}')"><span class="glyphicon glyphicon-remove"/></button>
                </form>
                {{repo.full_name}}
        </li>
        {%endfor%}
    </ul>
    {% endif %}
    {% if object.pk %}
    <div class="panel-group" id="repo-accordion">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#" href="#add-repo">
                        {% trans "+ Connect a new repository to this project" %}
                    </a>
                </h4>
            </div>
            <div id="add-repo" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form action="{% url 'repos:add_repo' object.pk %}" method="post">
                                {% csrf_token %}
                                <div class="fieldWrapper">
                                    {{ repo_form.full_name.label_tag }}
                                    <div class="input-group">
                                        <input id="{{repo_form.full_name.id_for_label}}" name="{{repo_form.full_name.html_name}}" maxlength="{{ repo_form.full_name.field.max_length }}" type="text" class="form-control">
                                          <span class="input-group-btn">
                                            <input class="btn btn-default" type="submit" onclick="return confirm('{% trans 'Are you sure you want to add this repo?' %}')" value="{% trans 'Add Repo' %}"></submit>
                                          </span>
                                    </div><!-- /input-group -->
                                </div>
                            </form>
                        </div><!-- /.col-lg-6 -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}


{% if False %}

        {% if object.repos and object.repos.all|length > 0 %}
    <hr>
    <p class="text-left"><strong>Owners: </strong></p>

    <ul class="list-group">
        {% for owner in owners %}
        <li class="list-group-item">
                <form role="inline-form" action="{% url 'repos:remove_owner' object.pk%}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="owner" value="{{owner.pk}}"/>
                    <button class="btn btn-link pull-right" type="submit" onclick="return confirm('{% trans 'Are you sure you want to remove this owner?' %}')"><span class="glyphicon glyphicon-remove"/></button>
                </form>
                <a href="{{owner.get_absolute_url}}">{{owner.nick}} ({{ owner.english_name }})</a>
        </li>
        {%endfor%}
    </ul>
    {% endif %}
    {% if object.pk %}
    <div class="panel-group" id="repo-accordion">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#" href="#add-owner">
                        {% trans "+ Add a new owner to this project" %}
                    </a>
                </h4>
            </div>
            <div id="add-owner" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form action="{% url 'repos:add_owner' object.pk %}" method="post">
                                {% csrf_token %}
                                    {{ owner_form.as_p }}
                                            <input class="btn btn-default" type="submit" onclick="return confirm('{% trans 'Are you sure you want to add this owner?' %}')" value="{% trans 'Add Owner' %}"></submit>
                            </form>
                        </div><!-- /.col-lg-6 -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endif %}


</div>

{% endblock %}

repos/templates/repos/project_list.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
      <li class="active">{%  trans "Projects" %}</li>
{% endblock %}

{% block simplecontent %}
    <ul class="list-group">
        {% for object in object_list %}
            <li class="list-group-item">
                <a href="{{ object.get_absolute_url }}">
                    {{ object }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

repos/templates/repos/project_update_form.html
{% extends "repos/project_form.html" %}
{% load i18n %}

{% block breadcrumbs %}
<li><a href="{%  url "repos:list" %}">{%  trans "Projects" %}</a></li>
<li class="active">{{ object.english_name }}</li>
{% endblock %}

{% block form_action %}{% url 'repos:project_update' object.pk %}{% endblock %}