choi/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from users import views

urlpatterns = patterns('',
    # Examples:
    url(r'^$',  TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^projects/', include('repos.urls', namespace='repos')),
    url(r'^skills/$',  views.skills, name='skills'),
    url(r'^skills/(\w+)/$',  views.skill_by_slug, name='skill_by_slug'),
    url(r'^admin/', include(admin.site.urls)),
)

repos/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from repos import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', views.ProjectView.as_view(), name="project_detail"),
    url(r'^create$', views.ProjectCreateView.as_view(), name="project_create"),
    url(r'^(?P<pk>\d+)/edit$', views.ProjectUpdateView.as_view(), name="project_update"),
    url(r'^(?P<pk>\d+)/add_repo$', views.add_repo, name="add_repo"),
    url(r'^remove_repo$', views.remove_repo, name="remove_repo"),
    url(r'^(?P<project>\d+)/add_owner$', views.add_owner, name="add_owner"),
    url(r'^(?P<project>\d+)/remove_owner', views.remove_owner, name="remove_owner"),
)

users/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from users import views
from users.models import NICK_PATTERN

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.HomeView.as_view(), name="list"),
    url(r'^(?P<slug>{})/$'.format(NICK_PATTERN), views.UserView.as_view(), name="detail"),
    url(r'^create$', views.UserCreateView.as_view(), name="user_create"),
    url(r'^(?P<slug>{})/edit$'.format(NICK_PATTERN), views.UserUpdateView.as_view(), name="user_update"),
)

users/models.py
import hashlib
import re
from django.contrib.auth.models import BaseUserManager
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from authtools.models import AbstractEmailUser
from django.utils.translation import ugettext_lazy as _
from repos.models import Project

NICK_PATTERN = r"[a-zA-Z][a-zA-Z0-9_]{3,15}"
NICK_RE = re.compile(NICK_PATTERN)
NICK_HELPTEXT = _("Nicks must start with an English letter, and contain at least 4 letters, numbers or "
                  "underscores, and may not be longer than 16 characters")


class UserManager(BaseUserManager):
    def create_user(self, nick, email, password=None, **kwargs):
        email = self.normalize_email(email)
        user = self.model(nick=nick, email=email, **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, **kwargs):
        user = self.create_user(**kwargs)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class PrivacyLevel(object):
    PUBLIC = 1
    COMMUNITY = 2
    PRIVATE = 3

    choices = (
        (PUBLIC, _('Public (All viewers)')),
        (COMMUNITY, _('Community members only')),
        (PRIVATE, _('Site administrators only')),
    )


class UserSkill(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=200, unique=True)

    def __unicode__(self):
        return self.name

    def count_users(self):
        return User.objects.filter(skills = self).count()


class User(AbstractEmailUser):
    nick = models.CharField(_('nick'), max_length=255, unique=True, validators=[
        RegexValidator(NICK_RE)
    ], help_text=NICK_HELPTEXT)
    privacy = models.IntegerField(_('profile viewable by'), choices=PrivacyLevel.choices, default=PrivacyLevel.PUBLIC)
    email_privacy = models.IntegerField(_('email viewable by'), choices=PrivacyLevel.choices,
                                        default=PrivacyLevel.COMMUNITY)

    english_name = models.CharField(_('name in English'), max_length=255, blank=True, null=True)
    hebrew_name = models.CharField(_('name in Hebrew'), max_length=255, blank=True, null=True)

    phone_number = models.CharField(_('phone number'), max_length=255, blank=True, null=True)
    phone_privacy = models.IntegerField(_('phone number viewable by'), choices=PrivacyLevel.choices,
                                        default=PrivacyLevel.COMMUNITY)

    biography = models.TextField(null=True, blank=True)

    github_username = models.CharField(_('github username'), max_length=255, unique=True, null=True, blank=True)

    facebook_username = models.CharField(_('facebook username'), max_length=255, unique=True, null=True, blank=True)
    facebook_privacy = models.IntegerField(_('facebook number viewable by'), choices=PrivacyLevel.choices,
                                        default=PrivacyLevel.COMMUNITY)
    
    skills = models.ManyToManyField(UserSkill, related_name="users", blank=True)
    

    objects = UserManager()

    REQUIRED_FIELDS = [
        'nick',
        'privacy',
    ]

    def get_full_name(self):
        return self.english_name if self.english_name else self.nick

    def get_short_name(self):
        return self.nick

    def gravatar_url(self):
        return "http://www.gravatar.com/avatar/{}?d=blank".format(hashlib.md5(self.email.lower()).hexdigest())

    @staticmethod
    def filter_by_skill(skill):
        return User.objects.filter(skills=skill)


    def save(self, *args, **kwargs):
        qs = User.objects.filter(nick__iexact=self.nick)
        if self.id:
            qs = qs.exclude(id=self.id)
        if qs.exists():
            raise ValidationError("Nick already in use")
        return super(User, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'slug': self.nick})

    def __unicode__(self):
        return self.get_full_name()

    class Meta:
        ordering = ['nick']
        verbose_name = _('user')
        verbose_name_plural = _('users')

users/forms.py
from users.models import User
import floppyforms as forms

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['privacy','password','nick',
                  'english_name','hebrew_name','email','email_privacy',
                  'phone_number','phone_privacy',
                  'facebook_username','facebook_privacy',
                  'biography','github_username','skills']

users/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.shortcuts import render, get_object_or_404
from users.models import User, UserSkill
from forms import EditUserForm

class HomeView(ListView):
    # TODO: show users according to privacy level
    model = User


class UserView(DetailView):
    # TODO: show users according to privacy level
    model = User
    slug_field = 'nick'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        commits = self.object.authored_commits.all()
        context['total_commits'] = len(commits)

        repo_commits = dict()
        for commit in commits:
            commit_repos = commit.repos.all()
            for commit_repo in commit_repos:
                repo = commit_repo.repo
                if not repo_commits.has_key(repo):
                    repo_commits[repo]=list()
                repo_commits[repo].append(commit)

        project_repo_commits = dict()
        for repo, commits in repo_commits.items():
            project = repo.project
            if not project_repo_commits.has_key(project):
                project_repo_commits[project] = dict()
                project_repo_commits[project]['total_commits']= 0
            project_repo_commits[project][repo]=commits
            project_repo_commits[project]['total_commits'] += len(commits)

        context['project_repo_commits'] = project_repo_commits
        return context


class UserCreateView(CreateView):
    model = User
    form_class = EditUserForm
    template_name_suffix = '_create_form'

class UserUpdateView(UpdateView):
    model = User
    form_class = EditUserForm
    slug_field = 'nick'
    template_name_suffix = '_update_form'
    def get_success_url(self):
        return self.object.get_absolute_url()
    
 
def skills(request):
    skillList = UserSkill.objects.all()

    return render(request, 'skills/skills.html', {
                            'skill_list': skillList,
                            })

def skill_by_slug(request, pk):
    skill=get_object_or_404(UserSkill, slug=pk)
    userList = User.filter_by_skill(skill)
    return render(request, 'skills/skill_users.html', {
                            'user_list': userList,
                            'skill': skill,
                            })

users/templates/users/user_create_form.html
{% extends "users/user_form.html" %}
{% load i18n %}

{% block breadcrumbs %}
    <li><a href="{%  url "users:list" %}">{%  trans "Users" %}</a></li>
    <li class="active">{% trans "New User" %}</li>
{% endblock %}

{% block form_action %}{% url 'users:user_create' %}{% endblock %}

users/templates/users/user_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
<li><a href="{%  url "users:list" %}">{%  trans "Users" %}</a></li>
<li class="active">{{ object.nick }}</li>
{% endblock %}

{% block content %}
<div class="well">
    <center>
        <img src="{{ object.gravatar_url }}?s=140" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
        <h3 class="media-heading">
            {{ object.nick }}
        </h3>
        <h3 class="media-heading"><small>{{ object.hebrew_name }} | {{ object.english_name }}</small></h3>
        <span><strong>Skills: </strong></span>
        {% for skill in object.skills.all %}
        <a href="{% url 'skill_by_slug' skill.slug %}">
        <span class="label label-info">
        	{{ skill }}
        </span>
        </a> &nbsp;
        {% endfor %}
        {% if user == object %}
          <br><small>(<a href="{% url 'users:user_update' object.nick %}">edit profile</a>)</small>
        {% endif %}
    </center>
    <hr>
    <p class="text-left"><strong>Email: </strong><br>
        <a href="mailto:{{object.email}}"> {{object.email }}</a></p>
        
    <hr>
        <p class="text-left"><strong>Bio: </strong><br>
            {{object.biography }}</p>

    <hr>
        <p class="text-left"><strong>Projects: </strong><br>
        	<ul>
        		{% for project in object.projects.all %}
        		<li><a href="{% url 'repos:project_detail' project.id %}">{{project}}</a></li>
        		{% endfor %}
        	</ul>
        </p>
    
    {% if object.github_username %}
    <hr>
        <p class="text-left"><strong>Github: </strong><br>
            User's Github page: <a href="http://github.com/{{ object.github_username }}" target="_blank">http://github.com/{{ object.github_username }}</a></p>
    {% endif %}
    
    {% if object.github_username and object.authored_commits.all|length > 0 %}
    <hr>
    <p class="text-left"><strong>Code Contributions: </strong></p>

    <div class="panel-group" id="all-accordion">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="" href="#collapseAll">
                        <strong>Total Commits:</strong> {{total_commits}}
                    </a>
                </h4>
            </div>
            <div id="collapseAll" class="panel-collapse collapse in">
                <div class="panel-body">
                    {% for project, repo_commits in project_repo_commits.items %}
                    <div class="panel-group" id="project-accordion{{forloop.counter}}">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="" href="#collapseProject{{forloop.counter}}">
                                        {{project.english_name}}: {{ repo_commits.total_commits}}
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseProject{{forloop.counter}}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    {% for repo, commits in repo_commits.items %}
                                    {% if not repo == 'total_commits' %}
                                    <div class="panel-group" id="repo-accordion">
                                        <div class="panel panel-warning">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a data-toggle="collapse" data-parent="#" href="#collapseRepo{{forloop.parentloop.counter}}{{forloop.counter}}">
                                                        {{repo.full_name}}: {{ commits | length}}
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapseRepo{{forloop.parentloop.counter}}{{forloop.counter}}" class="panel-collapse collapse">
                                                <div class="panel-body">
                                                    <ul class="list-group">
                                                        {%for commit in commits %}
                                                        <li class="list-group-item">{{commit.message}}</li>
                                                        {%endfor%}
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
    {% endif %}
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends "base.html" %}
{% load i18n %}

{% block simplecontent %}
    <ul class="list-group">
        <form action="{% block form_action %}{% endblock %}" method="post">{% csrf_token %}
            {{ form.as_ul }}
        <input type="submit" value="Submit" />
        </form>
    </ul>
{% endblock %}

users/templates/users/user_list.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
      <li class="active">{%  trans "Users" %}</li>
{% endblock %}

{% block simplecontent %}
    <ul class="list-group">
        {% for object in object_list %}
            <li class="list-group-item">
                <a href="{{ object.get_absolute_url }}">
                    <img src="{{ object.gravatar_url }}&s=20"/>
                    {{ object }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

users/templates/users/user_update_form.html
{% extends "users/user_form.html" %}
{% load i18n %}

{% block breadcrumbs %}
    <li><a href="{%  url "users:list" %}">{%  trans "Users" %}</a></li>
    <li class="active"><a href="{{ object.get_absolute_url }}">{{ object.nick }}</a></li>
{% endblock %}

{% block form_action %}{% url 'users:user_update' object.nick %}{% endblock %}